version: '3.8'

services:
  fast-media-kit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fast-media-container
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
      - U2NET_HOME=/app/.u2net
      - OMP_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
      - VECLIB_MAXIMUM_THREADS=1
      - NUMEXPR_NUM_THREADS=1
